### PR TITLE
Entire application rewritten to TypeScript and login system improved

### PR DESCRIPTION
**Pull request by Tsugumik**
### Rewritten to typescript
After several attempts, we have successfully migrated the entire project from Javascript to Typescript. This will allow us to make corrections and improvements much more efficiently, even after the release of version 4.0 with the backend in Rust. The project also uses Vite to make our lives easier.

### Improved login system
The previous login system was based on a rather clumsy localstorage of cookies and manually attaching them to every request to shinden.pl. This led to a lot of unexpected behaviour and errors that were very difficult to find. Now you can log in without any problems and watch anime that are invisible to anonymous users.

**The application is also subjectively faster after the changes, I have not measured this precisely**

New login system

New logo

### CODE REVIEW

**Review by KrzysztofStaronPBS — APPROVED** [review]
confirmed
papiez

**Review by KrzysztofStaronPBS — APPROVED** [review]
papiez

**Review by KrzysztofStaronPBS — APPROVED** [review]
confirmed
papiez

**Comment by Tsugumik** [comment]
> confirmed papiez [ papiez ](https://private-user-images.githubusercontent.com/152295449/312984200-b86623d9-dfd7-4917-9770-5845b3d2f523.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NDk4MzEsIm5iZiI6MTcxMDQ0OTUzMSwicGF0aCI6Ii8xNTIyOTU0NDkvMzEyOTg0MjAwLWI4NjYyM2Q5LWRmZDctNDkxNy05NzcwLTU4NDViM2QyZjUyMy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQyMDUyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTgxNzM4MzRiY2UyYjU2NTZjODI2YTYyNGI1YmY3NTVhMWFmMWNlYjM1MzU4NjUxYTk0OTczZTA0MWQ1YzE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ywq0NzI6V1Irh1W1FZ6MW9xob5BcQ7D8Ggok3qtF8Hg) [ ](https://private-user-images.githubusercontent.com/152295449/312984200-b86623d9-dfd7-4917-9770-5845b3d2f523.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NDk4MzEsIm5iZiI6MTcxMDQ0OTUzMSwicGF0aCI6Ii8xNTIyOTU0NDkvMzEyOTg0MjAwLWI4NjYyM2Q5LWRmZDctNDkxNy05NzcwLTU4NDViM2QyZjUyMy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQyMDUyMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTgxNzM4MzRiY2UyYjU2NTZjODI2YTYyNGI1YmY3NTVhMWFmMWNlYjM1MzU4NjUxYTk0OTczZTA0MWQ1YzE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ywq0NzI6V1Irh1W1FZ6MW9xob5BcQ7D8Ggok3qtF8Hg)

200w

**Pull request merged**
